#!/usr/bin/env python3
"""
verify_music_generation.py -- IP-1110's own build-time comparison check
(§8 Tests to Add). Not a test_rom.py runtime check (no PyBoy/ROM
involved) -- a direct Python-level comparison confirming every generated
sub-theme's note sequence is a pure transform (transposition and/or
duration scaling) of the main theme's own SONG data, per FR-7100's own
Acceptance Criteria ("derivable from the main theme's own via
transposition and/or duration scaling alone"). Mirrors worldgen.py's
own oracle-comparison precedent in spirit.

Run standalone: python3 verify_music_generation.py
"""
from music import SONG, THEME_TRANSFORMS, generate_theme_variations, _transpose, _encode_notes

def check(name, cond, detail=""):
    status = "PASS" if cond else "FAIL"
    print(f"[{status}] {name}" + (f"  ({detail})" if detail else ""))
    return cond

def main():
    all_pass = True
    variations = generate_theme_variations()

    all_pass &= check(
        "All eight non-Grass identities present",
        set(variations.keys()) == set(THEME_TRANSFORMS.keys()),
        f"got={sorted(variations.keys())}")

    for identity, (semitones, dur_scale) in THEME_TRANSFORMS.items():
        expected_notes = [
            (_transpose(f, semitones), max(1, round(d * dur_scale)))
            for f, d in SONG
        ]
        expected_bytes = _encode_notes(expected_notes)
        actual_bytes = variations[identity]
        all_pass &= check(
            f"{identity}: generated bytes match the recomputed pure-transform expectation",
            actual_bytes == expected_bytes,
            f"len_actual={len(actual_bytes)} len_expected={len(expected_bytes)}")
        all_pass &= check(
            f"{identity}: same note count as the main theme (no notes added/removed)",
            len(expected_notes) == len(SONG),
            f"identity_notes={len(expected_notes)} song_notes={len(SONG)}")
        all_pass &= check(
            f"{identity}: terminal 0xFF loop-back marker present",
            actual_bytes[-1] == 0xFF)

    grass_bytes = _encode_notes(SONG)
    from music import music_data
    all_pass &= check(
        "grass (main theme, zero-transform anchor): music_data() byte-identical to _encode_notes(SONG)",
        music_data() == grass_bytes)

    print()
    print("ALL CHECKS PASSED" if all_pass else "SOME CHECKS FAILED")
    return 0 if all_pass else 1

if __name__ == '__main__':
    raise SystemExit(main())
